Repository prosimcorp/rabbit-stalker, pull requests merged in 2023-05, with the labels that each got.

#1 Feat/add condition value additional sources
  README.md
  api/v1alpha1/workloadaction_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/rabbit-stalker.docplanner.com_workloadactions.yaml
  config/samples/rabbit-stalker_v1alpha1_workloadaction.yaml
  controllers/workloadaction_controller.go
  controllers/workloadaction_status.go
  controllers/workloadaction_sync.go
Labels: bug, enhancement, good first issue

#2 Feat: Add support for regex on queue names
  README.md
  api/v1alpha1/workloadaction_types.go
  config/crd/bases/rabbit-stalker.docplanner.com_workloadactions.yaml
  config/samples/rabbit-stalker_v1alpha1_workloadaction.yaml
  controllers/workloadaction_status.go
  controllers/workloadaction_sync.go
Labels: documentation, enhancement

#3 feat: Add cross-namespace credentials & make vhost optional on regex
  README.md
  api/v1alpha1/workloadaction_types.go
  config/crd/bases/rabbit-stalker.docplanner.com_workloadactions.yaml
  config/samples/rabbit-stalker_v1alpha1_workloadaction.yaml
  controllers/workloadaction_controller.go
  controllers/workloadaction_status.go
  controllers/workloadaction_sync.go
Labels: bug, enhancement
